# Generated by Django 4.2.9 on 2024-01-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recruitment_company', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ConditionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conditiontypes')),
                ('from_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('INTAKE', 'Intake'), ('FOLLOWUP', 'Follow-up'), ('COMPANY', 'Company')], max_length=50)),
                ('from_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conditiontypes')),
                ('from_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
